# Config file for automatic testing at travis-ci.org

language: python

python:
  - 2.7

env:
  - TOXENV=py27-django111
  - TOXENV=py27-django111-check
  - TOXENV=docs
  - TOXENV=flake8

cache:
  - pip

before_install:
  - pip install pip==10.0.1

install:
  - pip install -r requirements/travis.txt

script:
  - tox

after_success:
  - codecov

deploy:
  provider: pypi
  user: appsembler
  password:
    secure: PmktUfLAp7tOuDJbfkG8KuUC3enOR/biOqil7gGZKCgMHJ9JFbAlhmFMOXCy/t5PNqYW1Md6wvebnvbtDL3TDIdAGINif0iA6hxOFJnGM/4nHvIHfs7HkbsuWiBDNQSxyhyvmFLBosX4SQtWQguxngQIVK82jvL38HQAY+ys3gIuJ/T5TtkRwRdoxMqV4gqafCSypfMH1H6pnT/NNBvvOhxfdA2x5HGC81afBNeUWniZpuoN4/VC0PtdCLosA/FyqB99AbqqPaCVbci4uajSo+3Q0yU1AWVAOpdwBpgDIeeMm5oTYNyYQjkOB7Lounn9AG6gRIYOm7L2ir023SphFURZd6lH8J3RlmG4rc3SC1vMYz5JVEkYUHCezbTJJNzsSwIw8aFJtoK/0EaYyQt6Iqk+360tA0AEGRBXKiKLI5b3ku8Niimhmhi735+1sYw71LFOzzFYxVjjjTg25VRxj5Td2qDaT2xBmEOcDnySEznw7q96dDGINBNcbduEVEPhf2JLDB3v+J9WOHeuP66rIX5e5tzAe9O6aDWMuyJsnzseZ9BELyTUugOd8zzanl+RwdRGt14r4Di5hAL61X9Rs2YS7/qBzbkM7Mbw84FaxWA9x0dLx0DjTxRTxy36FAbzAW23fOgmnCIPkNn+MWswN96OdtFZiQoO9WTnEMTv3r8=
  distributions: sdist bdist_wheel
  on:
    tags: true
  skip_existing: true
