name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.8]
        tox-env:
          - py3-django2
          - py3-django2-check
          - docs
          - flake8
    steps:
     - uses: actions/checkout@v2
     - name: Set up Python ${{ matrix.python-version }}
       uses: actions/setup-python@v2
       with:
         python-version: ${{ matrix.python-version }}
     - name: Install dependencies
       run: |
         pip install tox
     - name: Test with tox
       run: tox -e ${{ matrix.tox-env }}
     - name: codecov
       uses: codecov/codecov-action@v1
       if: ${{ matrix.tox-env == 'py3-django2' }}
